simple_public_timeline/public_timeline/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#timeline'
  get '/via_js', to: 'tweets#via_js'

  get '/login', to: 'users#login'
  get '/register', to: 'users#register', as: 'register_user'
end

simple_public_timeline/public_timeline/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

simple_public_timeline/public_timeline/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

simple_public_timeline/public_timeline/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def via_js
    
  end
end

simple_public_timeline/public_timeline/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def timeline
    @users = UserFacade.new.user_posts
  end
end

simple_public_timeline/public_timeline/app/helpers/application_helper.rb
module ApplicationHelper
end

simple_public_timeline/public_timeline/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PublicTimeline</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'twitter', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

simple_public_timeline/public_timeline/app/views/tweets/via_js.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <h1>Twitter</h1>
    <div class="login-join">
      <%= link_to 'Login', login_path, class: 'login' %>
      
      <%= link_to 'Join Twitter', register_user_path, class: 'join' %>
    </div>
  </div>

  <div class="tweets-container">
    <div class="tweets-list">
    <hr>
    <h3>Recent Public Tweets</h3>
    <h4>What everyone on Twitter is talking about!</h4>
    <hr>
    </div>

    <div class="sidebar">
      <div class="create-account">
        <h5>Create Your Account</h5>
        <%= link_to 'Join!', register_user_path, class: 'join-button' %>
      </div>
      <h5>Already using Twitter from your phone? Click here</h5>
      <div class="language-select">
        <%= select_tag "language", options_for_select([['Select Language...', ''], 'English', 'Español', 'Français', 'Mandarin']), class: 'language-dropdown' %>
      </div>
    </div>
  </div>
  
 <%= javascript_include_tag 'via_js' %>   

</body>
</html>

simple_public_timeline/public_timeline/app/views/users/timeline.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <h1>Twitter</h1>
    <div class="login-join">
      <%= link_to 'Login', login_path, class: 'login' %>
      
      <%= link_to 'Join Twitter', register_user_path, class: 'join' %>
    </div>
  </div>

  <div class="tweets-container">
    <div class="tweets-list">
    <%= '_______________________________________________________________________________' %>
    <h3>Recent Public Tweets</h3>
    <h4>What everyone on Twitter is talking about!</h4>
    <%= '_______________________________________________________________________________' %>
      <% @users.each do |user| %>
        <div class="tweet">
          <%= image_tag(user.profile_image, alt: "#{user.username}'s profile pic", class: 'profile-image') if user.profile_image.present? %>
          <div class="content">
            <strong><%= user.username %></strong>
            <p><%= user.text %></p>
            <small><%= user.tweet_creation %> via <%= user.source %></small>
            <%= '________________________________________________________________________' %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="sidebar">
      <div class="create-account">
        <h5>Create Your Account</h5>
        <%= link_to 'Join!', register_user_path, class: 'join-button' %>
      </div>
      <h5>Already using Twitter from your phone? Click here</h5>
      <div class="language-select">
        <%= select_tag "language", options_for_select([['Select Language...', ''], 'English', 'Español', 'Français', 'Mandarin']), class: 'language-dropdown' %>
      </div>
    </div>
  </div>
</body>
</html>